# Generated by Django 5.0.6 on 2024-06-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_cartmodel_ordermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='unique_key',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
